config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :upload_informations
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upload_information.rb
class UploadInformation < ApplicationRecord
  belongs_to :user

  def self.as_csv
    CSV.generate do |csv|
      csv <<  column_names
      all.each do |upload_information|
        csv << upload_information.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_person_name



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_many :upload_informations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:user_id])
      devise_parameter_sanitizer.permit(:account_update, keys: [:user_id])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/upload_informations_controller.rb
class UploadInformationsController < ApplicationController
  before_action :set_upload_information, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /upload_informations or /upload_informations.json

  def index
    @upload_informations = UploadInformation.all

    respond_to do |format|
      format.html
      format.csv { send_data @upload_informations.as_csv}
    end
  end

  # GET /upload_informations/1 or /upload_informations/1.json
  def show
  end

  # GET /upload_informations/new
  def new

    @upload_information = UploadInformation.new

  end


  # GET /upload_informations/1/edit
  def edit
  end

  # POST /upload_informations or /upload_informations.json
  def create

    @upload_information = UploadInformation.new(upload_information_params)
    @upload_information.user = current_user

    respond_to do |format|
      if @upload_information.save
        format.html { redirect_to @upload_information, notice: "Upload information was successfully created." }
        format.json { render :show, status: :created, location: @upload_information }
      else
        format.html { render :new }
        format.json { render json: @upload_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /upload_informations/1 or /upload_informations/1.json
  def update
    respond_to do |format|
      if @upload_information.update(upload_information_params)
        format.html { redirect_to @upload_information, notice: "Upload information was successfully updated." }
        format.json { render :show, status: :ok, location: @upload_information }
      else
        format.html { render :edit }
        format.json { render json: @upload_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upload_informations/1 or /upload_informations/1.json
  def destroy
    @upload_information.destroy
    respond_to do |format|
      format.html { redirect_to upload_informations_url, notice: "Upload information was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_upload_information
    @upload_information = UploadInformation.find_by(id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def upload_information_params
    params.require(:upload_information).permit(:fornavn, :efternavn, :postnummer, :addresse, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/upload_informations_helper.rb
module UploadInformationsHelper
end

app/views/home/index.html.erb
<div class="max-w-lg mx-auto mt-16 text-center">
  <h1 class="mb-4 text-3xl font-black">Welcome to IpVision!</h1>
  <p class="text-lg leading-snug">Create a user or sign in to an existing one.</p>


  <% if user_signed_in? %>

  <%= link_to "Update Profile", new_upload_information_path, class: "btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="antialiased">
  <%= render "shared/head" %>

  <body class="font-sans font-normal leading-normal text-gray-800 bg-white">
    <%= render "shared/flash_notice" %>
    <%= render "shared/header" %>

    <main class="px-4 lg:px-10">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div class="bg-red-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
  <% if type == "notice" %>
    <div class="bg-green-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <% if content_for?(:title) %>
      <%= yield :title %> |
    <% end %>
    IpVision
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_header.html.erb
<header class="mb-4">
  <nav class="flex flex-wrap items-center justify-between px-3 py-3 text-gray-700 bg-gray-100 lg:px-10">
    <div class="flex items-center mr-6 flex-no-shrink">
      <%= link_to "IpVision", root_path, class:"link text-xl tracking-tight font-black" %>
    </div>
    <div class="block lg:hidden">
      <button class="flex items-center px-3 py-2 border border-gray-500 rounded text-grey hover:text-gray-600 hover:border-gray-600">
        <svg class="w-3 h-3 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="items-center block w-full text-center lg:flex-1 lg:flex lg:text-left">
      
      <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
        <% if user_signed_in? %>
          <%= link_to "Edit account", edit_user_registration_path, class: "btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-default mb-2 lg:mb-0 block" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default block" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/upload_informations/_form.html.erb
<%= form_with(model: upload_information) do |form| %>
  <% if upload_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upload_information.errors.count, "error") %> prohibited this upload_information from being saved:</h2>

      <ul>
        <% upload_information.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fornavn %>
    <%= form.text_field :fornavn %>
  </div>

  <div class="field">
    <%= form.label :efternavn %>
    <%= form.text_field :efternavn %>
  </div>

  <div class="field">
    <%= form.label :postnummer %>
    <%= form.text_field :postnummer %>
  </div>

  <div class="field">
    <%= form.label :addresse %>
    <%= form.text_field :addresse %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/upload_informations/edit.html.erb
<h1>Editing Upload Information</h1>

<%= render 'form', upload_information: @upload_information %>

<%= link_to 'Show', @upload_information %> |
<%= link_to 'Back', upload_informations_path %>

app/views/upload_informations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Upload Information</h1>

<table>
  <thead>
    <tr>
      <th>Fornavn</th>
      <th>Efternavn</th>
      <th>Postnummer</th>
      <th>Addresse</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @upload_informations.each do |upload_information| %>
      <tr>
        <td><%= upload_information.fornavn %></td>
        <td><%= upload_information.efternavn %></td>
        <td><%= upload_information.postnummer %></td>
        <td><%= upload_information.addresse %></td>
        <td><%= upload_information.user_id %></td>
        <td><%= link_to 'Show', new_upload_information_path, class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_upload_information_path(upload_information), class: 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', upload_information, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-red' %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>
<tr>  
      <h3>Download to CSV</h3>
      <td><%= link_to 'CSV Report', upload_informations_path(format: "csv"), class: 'btn btn-default' %></td>
      </tr>
      <%= link_to 'Upload New Information', new_upload_information_path, class: 'btn btn-default' %>

app/views/upload_informations/new.html.erb
<h1>New Upload Information</h1>

<%= render 'form', upload_information: @upload_information %>

<%= link_to 'Back', upload_informations_path %>

app/views/upload_informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fornavn:</strong>
  <%= @upload_information.fornavn %>
</p>

<p>
  <strong>Efternavn:</strong>
  <%= @upload_information.efternavn %>
</p>

<p>
  <strong>Postnummer:</strong>
  <%= @upload_information.postnummer %>
</p>

<p>
  <strong>Addresse:</strong>
  <%= @upload_information.addresse %>
</p>



<%= link_to 'Edit', edit_upload_information_path(@upload_information) %> |
<%= link_to 'Back', upload_informations_path %>